// <auto-generated />
using System;
using HybridAi.TestTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HybridAi.TestTask.Data.Migrations
{
    [DbContext(typeof(IpDbContext))]
    [Migration("20191209184631_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.CityBlockIpv4", b =>
                {
                    b.Property<string>("Network")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<short>("AccuracyRadius")
                        .HasColumnType("smallint");

                    b.Property<int>("CityLocationGeonameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAnonymousProxy")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSatelliteProvider")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PostalCode")
                        .HasColumnType("character varying(8)")
                        .HasMaxLength(8);

                    b.Property<int?>("RegistredCountryGeonameId")
                        .HasColumnType("integer");

                    b.Property<int?>("RepresentedCountryGeonameId")
                        .HasColumnType("integer");

                    b.HasKey("Network");

                    b.HasIndex("CityLocationGeonameId");

                    b.ToTable("CityBlocksIpv4s","dbo");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.CityBlockIpv6", b =>
                {
                    b.Property<string>("Network")
                        .HasColumnType("varchar(39)")
                        .HasMaxLength(39);

                    b.Property<short>("AccuracyRadius")
                        .HasColumnType("smallint");

                    b.Property<int>("CityLocationGeonameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAnonymousProxy")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSatelliteProvider")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PostalCode")
                        .HasColumnType("character varying(8)")
                        .HasMaxLength(8);

                    b.Property<int?>("RegistredCountryGeonameId")
                        .HasColumnType("integer");

                    b.Property<int?>("RepresentedCountryGeonameId")
                        .HasColumnType("integer");

                    b.HasKey("Network");

                    b.HasIndex("CityLocationGeonameId");

                    b.ToTable("CityBlocksIpv6s","dbo");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.CityLocation", b =>
                {
                    b.Property<int>("GeonameId")
                        .HasColumnType("int4");

                    b.Property<string>("ContinentCode")
                        .IsRequired()
                        .HasColumnType("character varying(8)")
                        .HasMaxLength(8);

                    b.Property<string>("CountryIsoCode")
                        .IsRequired()
                        .HasColumnType("character varying(8)")
                        .HasMaxLength(8);

                    b.Property<bool>("IsInEuropeanUnion")
                        .HasColumnType("boolean");

                    b.Property<string>("MetroCode")
                        .HasColumnType("character varying(4)")
                        .HasMaxLength(4);

                    b.Property<string>("Subdivision1IsoCode")
                        .HasColumnType("character varying(4)")
                        .HasMaxLength(4);

                    b.Property<string>("Subdivision2IsoCode")
                        .HasColumnType("character varying(4)")
                        .HasMaxLength(4);

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("GeonameId");

                    b.ToTable("CityLocations","dbo");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.DeCity", b =>
                {
                    b.Property<int>("GeonameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ContinentName")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<string>("CountryName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("LocaleCodeName")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Subdivision1Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Subdivision2Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("GeonameId");

                    b.HasIndex("LocaleCodeName");

                    b.ToTable("DeCities","dbo");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.EnCity", b =>
                {
                    b.Property<int>("GeonameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ContinentName")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<string>("CountryName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("LocaleCodeName")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Subdivision1Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Subdivision2Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("GeonameId");

                    b.HasIndex("LocaleCodeName");

                    b.ToTable("EnCities","dbo");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.EsCity", b =>
                {
                    b.Property<int>("GeonameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ContinentName")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<string>("CountryName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("LocaleCodeName")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Subdivision1Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Subdivision2Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("GeonameId");

                    b.HasIndex("LocaleCodeName");

                    b.ToTable("EsCities","dbo");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.FrCity", b =>
                {
                    b.Property<int>("GeonameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ContinentName")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<string>("CountryName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("LocaleCodeName")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Subdivision1Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Subdivision2Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("GeonameId");

                    b.HasIndex("LocaleCodeName");

                    b.ToTable("FrCities","dbo");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.JaCity", b =>
                {
                    b.Property<int>("GeonameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ContinentName")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<string>("CountryName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("LocaleCodeName")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Subdivision1Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Subdivision2Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("GeonameId");

                    b.HasIndex("LocaleCodeName");

                    b.ToTable("JaCities","dbo");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.LocaleCode", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(8)")
                        .HasMaxLength(8);

                    b.HasKey("Name");

                    b.ToTable("LocaleCodes");

                    b.HasData(
                        new
                        {
                            Name = "en"
                        },
                        new
                        {
                            Name = "de"
                        },
                        new
                        {
                            Name = "fr"
                        },
                        new
                        {
                            Name = "es"
                        },
                        new
                        {
                            Name = "ru"
                        },
                        new
                        {
                            Name = "ja"
                        },
                        new
                        {
                            Name = "zh-CN"
                        },
                        new
                        {
                            Name = "pt-BR"
                        });
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.PtBrCity", b =>
                {
                    b.Property<int>("GeonameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ContinentName")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<string>("CountryName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("LocaleCodeName")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Subdivision1Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Subdivision2Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("GeonameId");

                    b.HasIndex("LocaleCodeName");

                    b.ToTable("PtBrCities","dbo");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.RuCity", b =>
                {
                    b.Property<int>("GeonameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ContinentName")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<string>("CountryName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("LocaleCodeName")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Subdivision1Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Subdivision2Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("GeonameId");

                    b.HasIndex("LocaleCodeName");

                    b.ToTable("RuCities","dbo");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.ZhCnCity", b =>
                {
                    b.Property<int>("GeonameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ContinentName")
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<string>("CountryName")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("LocaleCodeName")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Subdivision1Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Subdivision2Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.HasKey("GeonameId");

                    b.HasIndex("LocaleCodeName");

                    b.ToTable("ZhCnCities","dbo");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.CityBlockIpv4", b =>
                {
                    b.HasOne("HybridAi.TestTask.Data.Models.CityLocation", "CityLocation")
                        .WithMany("CityBlockIpv4Collection")
                        .HasForeignKey("CityLocationGeonameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.CityBlockIpv6", b =>
                {
                    b.HasOne("HybridAi.TestTask.Data.Models.CityLocation", "CityLocation")
                        .WithMany("CityBlockIpv6Collection")
                        .HasForeignKey("CityLocationGeonameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.CityLocation", b =>
                {
                    b.HasOne("HybridAi.TestTask.Data.Models.DeCity", "DeCity")
                        .WithOne("CityLocation")
                        .HasForeignKey("HybridAi.TestTask.Data.Models.CityLocation", "GeonameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HybridAi.TestTask.Data.Models.EnCity", "EnCity")
                        .WithOne("CityLocation")
                        .HasForeignKey("HybridAi.TestTask.Data.Models.CityLocation", "GeonameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HybridAi.TestTask.Data.Models.EsCity", "EsCity")
                        .WithOne("CityLocation")
                        .HasForeignKey("HybridAi.TestTask.Data.Models.CityLocation", "GeonameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HybridAi.TestTask.Data.Models.FrCity", "FrCity")
                        .WithOne("CityLocation")
                        .HasForeignKey("HybridAi.TestTask.Data.Models.CityLocation", "GeonameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HybridAi.TestTask.Data.Models.JaCity", "JaCity")
                        .WithOne("CityLocation")
                        .HasForeignKey("HybridAi.TestTask.Data.Models.CityLocation", "GeonameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HybridAi.TestTask.Data.Models.PtBrCity", "PtBrCity")
                        .WithOne("CityLocation")
                        .HasForeignKey("HybridAi.TestTask.Data.Models.CityLocation", "GeonameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HybridAi.TestTask.Data.Models.RuCity", "RuCity")
                        .WithOne("CityLocation")
                        .HasForeignKey("HybridAi.TestTask.Data.Models.CityLocation", "GeonameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HybridAi.TestTask.Data.Models.ZhCnCity", "ZhCnCity")
                        .WithOne("CityLocation")
                        .HasForeignKey("HybridAi.TestTask.Data.Models.CityLocation", "GeonameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.DeCity", b =>
                {
                    b.HasOne("HybridAi.TestTask.Data.Models.LocaleCode", "LocaleCode")
                        .WithMany("DeCities")
                        .HasForeignKey("LocaleCodeName");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.EnCity", b =>
                {
                    b.HasOne("HybridAi.TestTask.Data.Models.LocaleCode", "LocaleCode")
                        .WithMany("EnCities")
                        .HasForeignKey("LocaleCodeName");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.EsCity", b =>
                {
                    b.HasOne("HybridAi.TestTask.Data.Models.LocaleCode", "LocaleCode")
                        .WithMany("EsCities")
                        .HasForeignKey("LocaleCodeName");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.FrCity", b =>
                {
                    b.HasOne("HybridAi.TestTask.Data.Models.LocaleCode", "LocaleCode")
                        .WithMany("FrCities")
                        .HasForeignKey("LocaleCodeName");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.JaCity", b =>
                {
                    b.HasOne("HybridAi.TestTask.Data.Models.LocaleCode", "LocaleCode")
                        .WithMany("JaCities")
                        .HasForeignKey("LocaleCodeName");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.PtBrCity", b =>
                {
                    b.HasOne("HybridAi.TestTask.Data.Models.LocaleCode", "LocaleCode")
                        .WithMany("PtBrCities")
                        .HasForeignKey("LocaleCodeName");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.RuCity", b =>
                {
                    b.HasOne("HybridAi.TestTask.Data.Models.LocaleCode", "LocaleCode")
                        .WithMany("RuCities")
                        .HasForeignKey("LocaleCodeName");
                });

            modelBuilder.Entity("HybridAi.TestTask.Data.Models.ZhCnCity", b =>
                {
                    b.HasOne("HybridAi.TestTask.Data.Models.LocaleCode", "LocaleCode")
                        .WithMany("ZhCnCities")
                        .HasForeignKey("LocaleCodeName");
                });
#pragma warning restore 612, 618
        }
    }
}
